apiVersion: v1
kind: Service
metadata:
  name: project-todo-backend-svc
spec:
  type: ClusterIP
  selector:
    app: project-todo-backend
  ports:
    - port: 2332
      protocol: TCP
      targetPort: 3001