apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./../../base
- backup/job.yaml

patches:
- path: broadcaster/deployment.yaml
- path: app/deployment.yaml

namespace: project
images:
- name: BACKUP
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-backup
  newTag: 4.10.1-14a3d07896f589f53fa43ca2a75580df5b1dd241
- name: TODO-APP
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-todo-app
  newTag: 4.10.1-14a3d07896f589f53fa43ca2a75580df5b1dd241
- name: TODO-BACKEND
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-todo-backend
  newTag: 4.10.1-14a3d07896f589f53fa43ca2a75580df5b1dd241
- name: TODO-BROADCASTER
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-todo-broadcaster
  newTag: 4.10.1-14a3d07896f589f53fa43ca2a75580df5b1dd241
- name: WIKIPEDIA
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-todo-wikipedia
  newTag: 4.10.1-14a3d07896f589f53fa43ca2a75580df5b1dd241
