apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./../../base
- backup/job.yaml

patches:
- path: broadcaster/deployment.yaml
- path: app/deployment.yaml

namespace: project
images:
- name: BACKUP
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-backup
  newTag: main-9d6783596358d00b36fae152035670af01f6e7be
- name: TODO-APP
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-todo-app
  newTag: main-9d6783596358d00b36fae152035670af01f6e7be
- name: TODO-BACKEND
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-todo-backend
  newTag: main-9d6783596358d00b36fae152035670af01f6e7be
- name: TODO-BROADCASTER
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-todo-broadcaster
  newTag: main-9d6783596358d00b36fae152035670af01f6e7be
- name: WIKIPEDIA
  newName: europe-north1-docker.pkg.dev/dwk-gke-455410/my-repository/project-todo-wikipedia
  newTag: main-9d6783596358d00b36fae152035670af01f6e7be
