apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-todo-broadcaster-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-todo-broadcaster
  template:
    metadata:
      labels:
        app: project-todo-broadcaster
    spec:   
      containers: 
      - name: todo-broadcaster
        image: TODO-BROADCASTER
        env:
        - name: NATS_URI
          valueFrom:
            configMapKeyRef:
              name: project-conf
              key: NATS_URI      
        resources:
          requests:
            memory: "50Mi"
            cpu: "20m"
          limits:
            memory: "100Mi"
            cpu: "50m"
